### ISSUE TITLE
Login text fields do not clear after being closed

### ISSUE THREAD

**Issue by SamueleDassatti** [IglooCloud/IglooAurora#40]
**Current Behaviour**
Login text fields keep their previous text even if the user leaves the page and comes back.

**Expected behavior**
Login text fields should be clear after the user changes page.

**Comment by jadach1** [comment]
Hi, can I please take this issue ?

**Comment by SamueleDassatti** [comment]
Yeah, for sure. If you have any doubt feel free to ask!

**Comment by jadach1** [comment]
Hi I have 2 questions.  Currently I am using 
   npm start 
or
   yarn build
to test changes on my local machine but to build after a change is quite time intensive, is there another way to set up a quick development testing env ?

Second question, when I access the localhost to view the app the "password" textfield is missing from the login page, this happens across IE, Firefox and Chrome, not sure if this was a known issue of if I did something to produce it myself?

thanks

**Comment by SamueleDassatti** [comment]
Hi,

if you use `yarn start` or `npm start` the locally hosted web app should refresh as soon as you make changes to its code, so those are the fastest ways to test changes. 

As for the password field you should see it after clicking on "next" in the log in page. The "next" button could create some problems due to a missing server-side feature, so feel free to override the goToPassword function with a function that actually redirects you to the password field.

Thank you for you contribution!

**Comment by jadach1** [comment]
Hi again, I placed a PR for this issue.

**Comment by SamueleDassatti** [comment]
Thank you, I'll review as soon as possible!
