### ISSUE TITLE
Remove some developer features from Aurora

### ISSUE THREAD

**Issue by SamueleDassatti** [IglooCloud/IglooAurora#62]
We should remove the "Create device/value/notification" dialogs from Aurora as it would make more sense to reserve those features for a future Igloo Partner Dashboard. This would streamline the settings experience in Aurora and make it easier to use for normal users.

The "Manage authorizations" and "Change server" dialog would still be available.

@ZaninAndrea what do you think?

**Comment by ZaninAndrea** [comment]
I would leave them for the time being as they can be useful for the beta developers, I would remove them only when introducing the Partner Dashboard
